{
 "title": "first",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service",
    "query": {
     "query": "label_values(istio_requests_total,destination_service_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "$service Request Rate (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(istio_requests_total{destination_service=\"$service.prod-app.svc.cluster.local\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$service 5xx Error Rate %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(istio_requests_total{\r\n  destination_service=\"$service.prod-app.svc.cluster.local\",\r\n  response_code=~\"5..\"\r\n}[1m]))\r\n/\r\nsum(rate(istio_requests_total{\r\n  destination_service=\"$service.prod-app.svc.cluster.local\"\r\n}[1m]))\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$service Availability (SLI)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "1 - (\r\n  sum(rate(istio_requests_total{\r\n    destination_service=\"$service.prod-app.svc.cluster.local\",\r\n    response_code=~\"5..\"\r\n  }[1m]))\r\n  /\r\n  sum(rate(istio_requests_total{\r\n    destination_service=\"$service.prod-app.svc.cluster.local\"\r\n  }[1m]))\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$service Latency p50",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.50,\r\n  sum by (le) (\r\n    rate(istio_request_duration_milliseconds_bucket{\r\n      destination_service=\"$service.prod-app.svc.cluster.local\"\r\n    }[1m])\r\n  )\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$service Latency p95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.95,\r\n  sum by (le) (\r\n    rate(istio_request_duration_milliseconds_bucket{\r\n      destination_service=\"$service.prod-app.svc.cluster.local\"\r\n    }[1m])\r\n  )\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$service Latency p99",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.99,\r\n  sum by (le) (\r\n    rate(istio_request_duration_milliseconds_bucket{\r\n      destination_service=\"$service.prod-app.svc.cluster.local\"\r\n    }[1m])\r\n  )\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}